### PR TITLE
fix: source map filename for mts and cts files

### LINKED ISSUE #5: Incorrect sourcefile for `.mts` and `.cts` files.
Because of https://github.com/esbuild-kit/core-utils/blob/develop/src/esbuild/index.ts#L45 it causes the source map output by esbuild to have the wrong file. This causes vscodes debugger to open a virtual `.ts` file (instead of the actual `.mts` file) when you go to debug.

### PR DESCRIPTION
**Pull request by DylanPiercey**
I believe this resolves #5. In my testing the debugger works correctly.

I have not yet had time to test if this causes https://github.com/evanw/esbuild/issues/1932 again.

### CODE REVIEW

**Comment by DylanPiercey** [comment]
Okay trying to reproduce https://github.com/evanw/esbuild/issues/1932 and it seems I'm unable. Even removing all of the extension handling code is seems esbuild is now doing the correct thing?

**Comment by privatenumber** [comment]
Thanks for the PR.

Do you have a test-case in mind (similar to the identifier minification one) for this?

**Comment by DylanPiercey** [comment]
@privatenumber I haven't tested but I imagine for this tone it'd be as simple as creating an error stack and asserting that the file name in the trace is accurate

**Comment by privatenumber** [comment]
> Okay trying to reproduce [evanw/esbuild#1932](https://github.com/evanw/esbuild/issues/1932) and it seems I'm unable. Even removing all of the extension handling code is seems esbuild is now doing the correct thing?

I am still able to reproduce it. Repro: https://github.com/privatenumber/issue-reproductions/tree/master/reproductions/evanw/esbuild/1932

**Comment by privatenumber** [comment]
The current changes are failing on cjs-loader tests.

**Pull request merged**
