### PR TITLE
Bump esbuild 0.15 -> 0.16

### PR DESCRIPTION
**Pull request by amitdahan**
# Summary

This PR bumps ESBuild 0.15 to 0.16.

(Wasn't sure whether there was a specific reason to stay on `~0.15`/`^0.15`)

### CODE REVIEW

**Comment by privatenumber** [comment]
Is there something you want from the upgrade?

**Comment by amitdahan** [comment]
Hey! No, nothing specific, and no rush at all.

Mostly wanted to help reduce dependency duplication, now that Vite 4 is using ESBuild 0.16 as well.

**Comment by LinusU** [comment]
This would be neat since we want to use the same version of ESBuild when testing (via `@esbuild-kit/esm-loader`) as when deploying (via `esbuild` directly). Right now we are stuck on ESBuild 0.15 because of this...

**Comment by trim21** [comment]
> Is there something you want from the upgrade?

esbuild 0.17 support new TS 5.0 beta features which is missing in 0.15/0.16

**Comment by privatenumber** [comment]
Feel free to open a PR

**Pull request closed without merging**
